.TH ukui-upower
.SH NAME
ukui-upower \- The power-manager Interface for the UKUI Desktop Environment
.SH DESCRIPTION
This module show power-manager Interface
.SH "REPORTING BUGS"
Report bugs to http://gitlab2.kylin.com/ukui/ukui-power-manager/issues
.SH "SEE ALSO"
.SS
Ukui PowerManager documentation can be found under "Help" by right-clicking on \fBukui-power-manager\fR.
Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P
