.TH ukui 桌面环境电源管理
.SH 名称
ukui-power-manager \- ukui 桌面环境电源管理
.SH 描述
ukui 桌面环境电源管理指的是桌面环境中负责电源，电池，锁屏，关闭显示器，注销，重启，等接口调用逻辑的组件
.p
其根本目的是为了功耗控制
.p

实现以下功能 
.P
1.读取内核电池信息并显示 
.P
2.设置空闲n分钟后进入 休眠/睡眠/关闭显示器 等功能
.P
3.设置合上盖子后 休眠/睡眠/关闭显示器等功能
.P
4.设置低电量自动进入省电模式
.P
.SH "用户手册"
http://kylin-desktop.gitee.io/doc/ukui/ukui-power-manager/
.p

.SH "疑问解答"
如果您有疑问，请在这里反馈，我们会及时进行解答 https://gitee.com/kylin-desktop/doc/issues
.p
