.TH ukui-power-manager
.SH NAME
ukui-power-manager \- The power-manager for the UKUI Desktop Environment
.SH DESCRIPTION
This module show power-manager Daemon
This program is a background process of power management, which is mainly responsible for controlling the idle operation, closing operation, and low power operation of the operating system. 
And monitor the action of plugging and unplugging the power cord and perform corresponding operations.
.SH "REPORTING BUGS"
Report bugs to http://gitlab2.kylin.com/ukui/ukui-power-manager/issues
.SH "SEE ALSO"
.SS
Ukui PowerManager documentation can be found under "Help" by right-clicking on \fBukui-power-manager\fR.
Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P
