.TH ukui-power-manager-tray 
.SH NAME
ukui-power-manager-tray \- The power-manager UI for the UKUI Desktop Environment
.SH DESCRIPTION
This module show power-manager widget
This process is mainly for displaying the power management tray and the main interface after opening the tray icon.
Currently, the main interface will show the user the current remaining power and remaining charging time. 
And provide users with an interface to enter the control panel to set related power operations. 
.SH "REPORTING BUGS"
Report bugs to http://gitlab2.kylin.com/ukui/ukui-power-manager/issues
.SH "SEE ALSO"
.SS
Ukui PowerManager documentation can be found under "Help" by right-clicking on \fBukui-power-manager\fR.
Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P
