.TH ukui "1" "2019-08-01" "UKUI 0.10.0" "UKUI Power Manager Module"
.SH NAME
ukui-power-manager \- The powermanagement for the UKUI Desktop Environment
.SH SYNOPSIS
.B ukui-power-manager
.br
.SH DESCRIPTION
The powermanagement for the UKUI Desktop Environment
.SH BEHAVIOR
The powermanagement for the UKUI Desktop Environment
.P
The powermanagement for the UKUI Desktop Environment
.SH "REPORTING BUGS"
Report bugs to https://github.com/ukui/ukui-power-manager/issues
.SH "SEE ALSO"
.P

