.TH ukui-power-management-server 
.SH NAME
ukui-power-management-server \- The power-manager Dbus Server for the UKUI Desktop Environment
.SH DESCRIPTION
This module show power-manager Dbus Server
This service provides corresponding interfaces for the power management background process, such as shutdown, hibernation, sleep, etc. 
The main corresponding interface is the corresponding interface provided by systemd. 
The service is treated as a SystemBus.
.SH "REPORTING BUGS"
Report bugs to http://gitlab2.kylin.com/ukui/ukui-power-manager/issues
.SH "SEE ALSO"
.SS
Ukui PowerManager documentation can be found under "Help" by right-clicking on \fBukui-power-manager\fR.
Further information may also be available at: http://wiki.ukui-desktop.org/docs
.P
