.TH "UKUI-POWER-MANAGER-TRAY" "1" "29 March,2006" "" ""
.SH NAME
ukui-power-manager-tray \- UKUI power manager system tray
.SH SYNOPSIS
\fBukui-power-manager-tray\fR [ \fB\-\-verbose\fR ] [ \fB\-\-debug\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBukui-power-manager-tray\fR is the panel applet of the UKUI power management.
.PP
It supports features such as suspending, hibernating, screen blanking, cpu frequency switching and more.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.TP
\fB\-\-debug\fR
Only show specific debugging options. Useful for developers only.
.SH "SEE ALSO"
.PP
ukui-power-preferences (1).
.SH "AUTHOR"
.PP
This manual page was written by Oliver Grawert <ogra@ubuntu.com> for
the Debian system and updated by Ow Mun Heng <nikeow@yahoo.com>
