.TH "UKUI-POWER-STATISTICS" "1" "11 December, 2007" "" ""
.SH NAME
ukui-power-policy \- UKUI power policy
.SH SYNOPSIS
\fBukui-power-policy\fR [ \fB\-\-verbose\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBukui-power-policy\fR control the power policy of the system.
.PP
It control the power policy of the system.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.SH "SEE ALSO"
.PP
ukui-power-manager (1), ukui-power-preferences (1).
.SH "AUTHOR"
.PP
This manual page was written by He Puyao <hepuyao@kylinos.cn>.
