.TH "UKUI-POWER-STATISTICS-QT" "1" "11 December, 2019" "" ""
.SH NAME
ukui-power-statistics-qt \- UKUI power statistics GUI(Qt)
.SH SYNOPSIS
\fBukui-power-statistics-qt\fR [ \fB\-\-verbose\fR ] [ \fB\-\-help\fR ]
.SH "DESCRIPTION"
\fBukui-power-statistics-qt\fR is the gui program for the ukui power management infrastructure.
.PP
It allows users to visualize the power consumption of laptop hardware.
.SH "OPTIONS"
.TP
\fB\-\-help\fR
Show summary of options.
.TP
\fB\-\-verbose\fR
Show extra debugging.
.SH "SEE ALSO"
.PP
ukui-power-manager (1), ukui-power-preferences (1).
.SH "AUTHOR"
.PP
This manual page was written by Jiang Hong <jianghong@kylinos.cn>.
