/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp org.ukui.upower.xml -i dbus.h -a dbus-ukuipower
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus-ukuipower.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class UpowerAdaptor
 */

UpowerAdaptor::UpowerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

UpowerAdaptor::~UpowerAdaptor()
{
    // destructor
}

QString UpowerAdaptor::CanHibernate()
{
    // handle method call org.ukui.upower.CanHibernate
    QString out0;
    QMetaObject::invokeMethod(parent(), "CanHibernate", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString UpowerAdaptor::DaemonVersion()
{
    // handle method call org.ukui.upower.DaemonVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "DaemonVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString UpowerAdaptor::IconName()
{
    // handle method call org.ukui.upower.IconName
    QString out0;
    QMetaObject::invokeMethod(parent(), "IconName", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool UpowerAdaptor::IsPresent()
{
    // handle method call org.ukui.upower.IsPresent
    bool out0;
    QMetaObject::invokeMethod(parent(), "IsPresent", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool UpowerAdaptor::LowBattery()
{
    // handle method call org.ukui.upower.LowBattery
    bool out0;
    QMetaObject::invokeMethod(parent(), "LowBattery", Q_RETURN_ARG(bool, out0));
    return out0;
}

QString UpowerAdaptor::MachineType()
{
    // handle method call org.ukui.upower.MachineType
    QString out0;
    QMetaObject::invokeMethod(parent(), "MachineType", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool UpowerAdaptor::OnBattery()
{
    // handle method call org.ukui.upower.OnBattery
    bool out0;
    QMetaObject::invokeMethod(parent(), "OnBattery", Q_RETURN_ARG(bool, out0));
    return out0;
}

double UpowerAdaptor::Percentage()
{
    // handle method call org.ukui.upower.Percentage
    double out0;
    QMetaObject::invokeMethod(parent(), "Percentage", Q_RETURN_ARG(double, out0));
    return out0;
}

int UpowerAdaptor::State()
{
    // handle method call org.ukui.upower.State
    int out0;
    QMetaObject::invokeMethod(parent(), "State", Q_RETURN_ARG(int, out0));
    return out0;
}

int UpowerAdaptor::TimeToEmpty()
{
    // handle method call org.ukui.upower.TimeToEmpty
    int out0;
    QMetaObject::invokeMethod(parent(), "TimeToEmpty", Q_RETURN_ARG(int, out0));
    return out0;
}

int UpowerAdaptor::TimeToFull()
{
    // handle method call org.ukui.upower.TimeToFull
    int out0;
    QMetaObject::invokeMethod(parent(), "TimeToFull", Q_RETURN_ARG(int, out0));
    return out0;
}

QString UpowerAdaptor::UPowerVersion()
{
    // handle method call org.ukui.upower.UPowerVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "UPowerVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

